# Generated by Django 2.1.5 on 2020-07-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=40)),
                ('area', models.TextField()),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalCite',
        ),
    ]
