# Generated by Django 2.1.5 on 2020-07-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cite',
            name='doctor',
        ),
        migrations.AddField(
            model_name='cite',
            name='doctor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cita.Doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='code',
            field=models.IntegerField(),
        ),
    ]
