# Generated by Django 2.1.5 on 2020-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_auto_20200723_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
