# Generated by Django 3.0.7 on 2020-08-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0006_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='qwertyuiop', max_length=10),
            preserve_default=False,
        ),
    ]
