# Generated by Django 3.0.7 on 2020-08-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0007_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
