# Generated by Django 3.0.7 on 2020-08-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0008_auto_20200805_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cite',
            name='area',
            field=models.TextField(max_length=30),
        ),
    ]
