# Generated by Django 3.0.7 on 2020-08-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0010_auto_20200805_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='email',
            field=models.CharField(default='@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
